### ISSUE TITLE
 anyone try?

### ISSUE THREAD

**Issue by tanerik** [Farhad-Shabani/BinanceAlgorithmTrading_RSIBOT#2]
Have you been tested? How are the results?

**Comment by Farhad-Shabani** [comment]
I have backtested from 2018. The results were mostly better than hold. You might need some minor adjustments for optimal returns in different assets.

**Comment by tanerik** [comment]
Bro thank you for answers. I want to test your script. Is it necessary to enter only api keys? writes test in config.py file. This is test api? and There are some lines that I don't understand. What is this line ? def dat_secrets(): What should i write. 
Do we need to install MySQL databases?

**Comment by tanerik** [comment]
1 - Im following pip install -r requirements.txt but 
It gives this error.
C:\Python\RSI_TradingBot_BinanceAPI-main>python runbot.py
Traceback (most recent call last):
  File "runbot.py", line 5, in <module>
    from MainStrategy import AlgorithmTrading
  File "C:\Python\RSI_TradingBot_BinanceAPI-main\MainStrategy.py", line 2, in <module>
    import talib
ModuleNotFoundError: No module named 'talib'

2- I tried to install the talib library
C:\Python\RSI_TradingBot_BinanceAPI-main>pip install talib
ERROR: Could not find a version that satisfies the requirement talib (from versions: none)
ERROR: No matching distribution found for talib

3-2- I tried to install the ta-lib library
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
4- I Installed C++14 but not work :(

**Comment by tanerik** [comment]
I solved problem. This is my fold. :( I installed ta-lib and run now. But my money balance 1000. This is test mode ??? How can change live mode ?

**Comment by tanerik** [comment]
:) I solved broThis is my fold again. Now trying your scrpt.

**Comment by tanerik** [comment]
The script worked for 1 hour and wrote 2113 lines. Then logged out of python. Why might he have logged out?

**Comment by Farhad-Shabani** [comment]
- Yes, you have to insert your Binance API keys into the config.py
- I used PostgreSQL as the DB. You have to configure def dat_secrets() with your DB specs or write some adjusted codes to work with your own database.
- Please make sure about libraries version. I don't remember exactly, but some latest versions are not compatible. Seems you have handled it.
- The default cash: 1000 is set for the backtest mode.
- About logging out of python, some code should be added to check and maintain the Socket persistently connected.
Actually, it was the first version, needed to develop more, but the results are very concrete. (even up to 10X return in backtests with only one indicator (RSI), by the combination of different timeframes)
 I haven't time to upgrade it. Would be my pleasure if you collaborate and commit any updates.
